### ISSUE TITLE
nezha-agent一键降级到指定版本脚本执行异常

### ISSUE THREAD

**Issue by astemo6** [eooce/scripts#1]
提示下载失败，判定无法连接GitHub，部署在azure的，可正常连接外网，且用哪吒官方最新的安装脚本可以安装。

请输入选择 [0-13]: 8
> 安装监控Agent指定版本18.0
正在下载监控端
> 修改Agent配置
文件下载失败，请检查本机能否连接 raw.githubusercontent.com/naiba/nezha/master

**Comment by eooce** [comment]
安装你用官方的安装，再降级agent用bash <(curl -Ls https://raw.githubusercontent.com/eooce/scripts/master/agent.sh)

**Comment by astemo6** [comment]
用这个脚本降级会提示这个错误：
           
开始尝试重启agent服务
Failed to restart nezha-agent.service: Unit nezha-agent.service is masked.
nezha-agent服务重启失败

**Comment by astemo6** [comment]
谢谢您，已经解决
